#!/usr/bin/env bash
set -e

apt-get update && apt-get install -y gfortran-8 && apt-get clean all

mkdir ./gfortran-8
sudo ln -s /usr/bin/gfortran-8 ./gfortran-8/gfortran
export PYTHONPATH=$PYTHONPATH:$PWD/gfortran-8
pip install camb

